version: "3.9"

services:
  db:
    image: mariadb:11.4
    environment:
      TZ: Asia/Bangkok
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MARIADB_DATABASE: ${DB_NAME:-queue_db}
      MARIADB_USER: ${DB_USER:-queue_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-queue_pass}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
